#!/usr/bin/env bash
# Init script: start, stop, restat the manage_my_process daemon
PIDFILE="/var/run/my_process.pid"
SCRIPT="./manage_my_process"

start()  {
	if [ -f "$PIDFILE" ]; then
		echo "Already running?"
		exit 1
	fi
	$SCRIPT &
	echo $! > "$PIDFILE"
	echo "manage_my_process started"
}

stop() {
	if [ ! -f "$PIDFILE" ]; then
		echo "Not running?"
		exit 1
	fi
	kill "$(cat "$PIDFILE")"
	rm -f "$PIDFILE"
	echo "manage_my_process stopped"
}

restart() {

	stop > /dev/null 2>&1
	start > /dev/null 2&1
	echo "manage_my_process restarted"
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		exit 1
		;;
esac
